// @ts-check
import tsEslint from 'typescript-eslint';
import nextPlugin from '@next/eslint-plugin-next';

// Files belonging to Next.js frontend apps — get Next.js rules + dep-direction enforcement.
const NEXT_APP_FILES = [
  'apps/b2c-web/**/*.ts',
  'apps/b2c-web/**/*.tsx',
  'apps/b2b-portal/**/*.ts',
  'apps/b2b-portal/**/*.tsx',
  'apps/admin/**/*.ts',
  'apps/admin/**/*.tsx',
];

const ALL_BB = [
  '@bb/domain',
  '@bb/supplier-contract',
  '@bb/ledger',
  '@bb/payments',
  '@bb/rewards',
  '@bb/documents',
  '@bb/reseller',
  '@bb/rate-intelligence',
  '@bb/ui',
  '@bb/config',
  '@bb/db',
  '@bb/testing',
];

// Backend-internal packages that frontend apps must never import (ADR-011).
const BACKEND_INTERNAL = [
  '@bb/ledger',
  '@bb/payments',
  '@bb/rewards',
  '@bb/documents',
  '@bb/reseller',
  '@bb/supplier-contract',
  '@bb/rate-intelligence',
  '@bb/db',
];

function forbid(allowed, message) {
  return ALL_BB.filter((p) => !allowed.includes(p)).map((name) => ({
    group: [name],
    message: message.replace('{name}', name),
  }));
}

export default tsEslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/node_modules/**',
      '**/*.js',
      '**/*.mjs',
      // Auto-generated by Next.js on first build; must not be linted
      '**/next-env.d.ts',
    ],
  },

  ...tsEslint.configs.recommended,

  {
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
    },
  },

  // --- Next.js plugin for all three frontend apps ---
  {
    files: NEXT_APP_FILES,
    plugins: {
      '@next/next': nextPlugin,
    },
    settings: {
      next: {
        rootDir: ['apps/b2c-web', 'apps/b2b-portal', 'apps/admin'],
      },
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      // App Router apps have no pages/ directory; this rule scans pages/ and
      // errors when the directory is absent. Turn it off for all three apps.
      '@next/next/no-html-link-for-pages': 'off',
    },
  },

  // --- Dependency direction enforcement (ADR-011) ---

  {
    // domain: zero internal dependencies
    files: ['packages/domain/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        { patterns: forbid(['@bb/domain'], "packages/domain must have zero internal dependencies. Remove '{name}'.") },
      ],
    },
  },
  {
    // supplier-contract: only @bb/domain
    files: ['packages/supplier-contract/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        { patterns: forbid(['@bb/domain', '@bb/supplier-contract'], "packages/supplier-contract may only depend on @bb/domain. Remove '{name}'.") },
      ],
    },
  },
  {
    // rate-intelligence: only @bb/domain
    // pricing imports rate-intelligence — never the reverse (ADR-015)
    files: ['packages/rate-intelligence/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        { patterns: forbid(['@bb/domain', '@bb/rate-intelligence'], "packages/rate-intelligence may only depend on @bb/domain. Remove '{name}'.") },
      ],
    },
  },
  {
    // ledger: only @bb/domain
    files: ['packages/ledger/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        { patterns: forbid(['@bb/domain', '@bb/ledger'], "packages/ledger may only depend on @bb/domain. Remove '{name}'.") },
      ],
    },
  },
  {
    // payments: @bb/domain + @bb/ledger
    files: ['packages/payments/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        { patterns: forbid(['@bb/domain', '@bb/ledger', '@bb/payments'], "packages/payments may only depend on @bb/domain and @bb/ledger. Remove '{name}'.") },
      ],
    },
  },
  {
    // reseller: only @bb/domain
    files: ['packages/reseller/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        { patterns: forbid(['@bb/domain', '@bb/reseller'], "packages/reseller may only depend on @bb/domain. Remove '{name}'.") },
      ],
    },
  },
  {
    // documents: @bb/domain + @bb/ledger (read) + @bb/reseller (branding)
    files: ['packages/documents/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        { patterns: forbid(['@bb/domain', '@bb/ledger', '@bb/reseller', '@bb/documents'], "packages/documents may only depend on @bb/domain, @bb/ledger, and @bb/reseller. Remove '{name}'.") },
      ],
    },
  },
  {
    // db: no @bb dependencies — pure pg.Pool wrapper, no domain coupling
    files: ['packages/db/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        { patterns: forbid(['@bb/db'], "packages/db has no @bb dependencies. Remove '{name}'.") },
      ],
    },
  },
  {
    // Frontend apps: never import backend-internal packages
    files: NEXT_APP_FILES,
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: BACKEND_INTERNAL.map((name) => ({
            group: [name],
            message: `Frontend apps must not import backend-internal packages. Remove '${name}'.`,
          })),
        },
      ],
    },
  },
);
